use_kl_loss=False
adv_estimator=grpo
n_rollout=4
use_dynamic_bsz=True
lr=1e-6
model_path=/mnt/public/algm/models/Qwen2.5-3B-Instruct
# model_path=/mnt/public/algm/models/Qwen3-4B-Instruct-2507
# model_path=/mnt/public/algm/models/Qwen2.5-0.5B-Instruct
gpu_memory_utilization=0.6
rollout_mode=sync  # async rollout会使用agent loop manager
rollout_tp_size=1
rollout_backend=vllm
reward_function_path=/mnt/public/algm/yzy/train_repos/verl/verl/utils/reward_score/toolrl.py
reward_manager=toolrl

export EXPERIMENT_NAME="qwen2_5_3b_toolrl_rlla_4k"
# export EXPERIMENT_NAME="qwen2_5_0_5b_toolrl_rlla_4k"
# export EXPERIMENT_NAME="qwen3_4b_inst_toolrl_rlla_4k"

export WITHLENGTH=0
export REFINEDREWARD=0
export COARSEREWARD=0
export STRICTMATCH=0
export CORRECTMAX1=0
export MAX1STEP30MAX3=0
export SCHEDULEREWARD=0
export SCHEDULELENGTH=0


PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 algorithm.adv_estimator=${adv_estimator} \
 reward_model.enable=False \
 reward_model.reward_manager=${reward_manager} \
 data.train_files=/mnt/public/algm/yzy/train_repos/ToolRL/dataset/rlla_4k/train.parquet \
 data.val_files=/mnt/public/algm/yzy/train_repos/ToolRL/dataset/rlla_4k/test.parquet \
 data.train_batch_size=128 \
 data.max_prompt_length=3072 \
 data.max_response_length=1024 \
 data.filter_overlong_prompts=True \
 data.truncation='error' \
 actor_rollout_ref.model.path=${model_path} \
 actor_rollout_ref.rollout.mode=${rollout_mode} \
 actor_rollout_ref.model.enable_gradient_checkpointing=True \
 actor_rollout_ref.actor.fsdp_config.param_offload=False \
 actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
 actor_rollout_ref.actor.optim.lr=${lr} \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.model.use_remove_padding=True \
 actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
 actor_rollout_ref.actor.ppo_max_token_len_per_gpu=16384 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.name=${rollout_backend} \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=${rollout_tp_size} \
 actor_rollout_ref.rollout.gpu_memory_utilization=${gpu_memory_utilization} \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.n=${n_rollout} \
 custom_reward_function.path=${reward_function_path} \
 custom_reward_function.name=compute_score \
 actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
 critic.optim.lr=1e-5 \
 critic.model.path=${model_path} \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.logger='["console","wandb"]' \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.experiment_name=${EXPERIMENT_NAME} \
 trainer.save_freq=50 \
 trainer.test_freq=50 \
 trainer.total_epochs=5 2>&1 | tee verl_demo.log
